basePath: /
definitions:
  auth.AuthResponse:
    properties:
      id:
        type: string
      token:
        type: string
    type: object
  auth.LoginRequest:
    properties:
      email:
        type: string
      password:
        maxLength: 32
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  auth.RegisterRequest:
    properties:
      email:
        type: string
      name:
        maxLength: 50
        minLength: 3
        type: string
      password:
        maxLength: 32
        minLength: 8
        type: string
    required:
    - email
    - name
    - password
    type: object
  media.MediaResponse:
    properties:
      id:
        type: string
      url:
        type: string
    type: object
  posts.PostResponse:
    properties:
      content:
        type: string
      id:
        type: string
      media:
        items:
          $ref: '#/definitions/media.MediaResponse'
        type: array
    type: object
  posts.PostsResponse:
    properties:
      posts:
        items:
          $ref: '#/definitions/posts.PostResponse'
        type: array
    type: object
  shared.ErrorResponse:
    properties:
      error:
        type: string
      status:
        type: integer
    type: object
  shared.MessageResponse:
    properties:
      message:
        type: string
    type: object
  users.UpdateProfileRequest:
    properties:
      bio:
        maxLength: 500
        minLength: 3
        type: string
      image:
        type: string
      lastname:
        maxLength: 50
        minLength: 3
        type: string
      name:
        maxLength: 50
        minLength: 3
        type: string
    type: object
info:
  contact: {}
  description: This is a social media API that allows users to create posts, like
    posts, and follow other users.
  title: Social Media API
  version: "0.1"
paths:
  /:
    get:
      description: Returns a simple greeting
      produces:
      - text/plain
      responses:
        "200":
          description: Hello, World!
          schema:
            type: string
      summary: Hello World
      tags:
      - Testing
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      description: Login a user with the provided credentials
      parameters:
      - description: User login credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.AuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
      summary: Login a user
      tags:
      - auth
  /api/v1/auth/register:
    post:
      consumes:
      - application/json
      description: Register a new user with the provided details
      parameters:
      - description: User registration details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.AuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
      summary: Register a new user
      tags:
      - auth
  /api/v1/posts:
    post:
      consumes:
      - multipart/form-data
      description: Create a new post with the provided content
      parameters:
      - description: Post content
        in: formData
        name: content
        type: string
      - description: Attached files
        in: formData
        name: files
        type: file
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/shared.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Create a new post
      tags:
      - posts
  /api/v1/posts/{id}:
    delete:
      description: Delete a post by its ID
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/shared.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
      summary: Delete a post
    put:
      description: Update a post by its ID
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/shared.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
      summary: Update a post
  /api/v1/posts/suggested:
    get:
      description: Get suggested posts for the authenticated user
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/posts.PostsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
      summary: Get suggested posts
  /api/v1/posts/user/{id}:
    get:
      description: Get all posts by a user
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/posts.PostsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
      summary: Get posts by user
  /api/v1/users/{id}:
    delete:
      description: Deletes the user with the given ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      responses: {}
      security:
      - BearerAuth: []
      summary: Delete user
      tags:
      - users
    get:
      description: Get user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get user by ID
      tags:
      - users
    patch:
      consumes:
      - application/json
      description: Update user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/users.UpdateProfileRequest'
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Update user
      tags:
      - users
  /api/v1/users/follow/{id}:
    put:
      consumes:
      - application/json
      description: Toggles the follow status between two users. If the user is already
        following the target, unfollows them. If not, follows them.
      parameters:
      - description: user ID to follow/unfollow
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Toggle follow status between two users
      tags:
      - users
  /api/v1/users/suggest:
    get:
      consumes:
      - application/json
      description: Returns a list of suggested users for the authenticated user
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get suggested users
      tags:
      - users
schemes:
- http
securityDefinitions:
  BearerAuth:
    description: Type Bearer followed by a space and then the token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
